export const jumps = [
  {
    jumpNumber: 1,
    date: "2022-07-15",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description:
      "Great first jump of the day. Front flip exit. Good landing pattern & swoop.",
    jumpType: "angle",
  },
  {
    jumpNumber: 2,
    date: "2022-07-15",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    jumpType: "belly",
  },
  {
    jumpNumber: 3,
    date: "2022-07-20",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Back flip exit.",
    jumpType: "belly",
  },
  {
    jumpNumber: 4,
    date: "2022-07-20",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "great landing!",
    jumpType: "belly",
  },
  {
    jumpNumber: 5,
    date: "2022-07-20",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 6,
    date: "2022-07-21",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 7,
    date: "2022-07-21",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 8,
    date: "2022-07-21",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 9,
    date: "2022-07-23",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 10,
    date: "2022-07-23",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 11,
    date: "2022-07-15",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description:
      "Great first jump of the day. Front flip exit. Good landing pattern & swoop.",
    // jumpType: 'angle',
  },
  {
    jumpNumber: 12,
    date: "2022-07-15",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 13,
    date: "2022-07-20",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Back flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 14,
    date: "2022-07-20",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "great landing!",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 15,
    date: "2022-07-20",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 13500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 16,
    date: "2022-07-21",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "Front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 17,
    date: "2022-07-21",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "front flip exit.",
    // jumpType: 'belly',
  },
  {
    jumpNumber: 18,
    date: "2022-07-21",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "front float exit.",
    // jumpType: 'angle',
  },
  {
    jumpNumber: 19,
    date: "2022-07-23",
    aircraft: "Kodiak",
    equipment: "Falcon 260",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "rear float exit.",
    // jumpType: 'head down',
  },
  {
    jumpNumber: 20,
    date: "2022-07-23",
    aircraft: "Kodiak",
    equipment: "PD 210",
    exitAltitude: 5500,
    pullAltitude: 3500,
    freeFallTime: 60,
    jumpers: 1,
    description: "back flip exit.",
    // jumpType: 'angle',
  },
];
